config/routes.rb
Rails.application.routes.draw do
  root to: 'stretches#index'

  resources :stretches, only: [:index, :show]
  resources :body_areas, only: [:show, :index]

  resources :users, only: [:new, :create, :show] do
    resources :favorites, only: [:create, :destroy] do
      resources :notes, only: [:new, :create, :destroy, :edit, :update]
    end
  end


  resources :admins, only: [:show]
  namespace :admin do
    resources :stretches, only: [:new, :create, :edit, :update, :destroy]
    resources :body_areas, only: [:new, :create]
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/body_area.rb
class BodyArea < ActiveRecord::Base
  has_many :body_area_stretches
  has_many :stretches, through: :body_area_stretches
  validates :name, presence: true, uniqueness: true
end

app/models/body_area_stretch.rb
class BodyAreaStretch < ApplicationRecord
  belongs_to :body_area
  belongs_to :stretch
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :stretch
  has_one :note
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :favorite
end

app/models/stretch.rb
class Stretch < ActiveRecord::Base
  validates :name, presence: true
  validates :description, presence: true
  validates :picture, presence: true

  has_many :body_area_stretches
  has_many :body_areas, through: :body_area_stretches
  has_many :favorites
  has_many :users, through: :favorites
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :favorites
  has_many :stretches, through: :favorites

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true

  enum role: ["default", "admin"]
end

app/controllers/admin/body_areas_controller.rb
class Admin::BodyAreasController < ApplicationController
  before_action :require_admin

  def new
    @body_area = BodyArea.new
  end

  def create
    @body_area = BodyArea.new(body_area_params)
    if @body_area.save
      redirect_to body_areas_path, alert: "#{@body_area.name} has been created!"
    else
      redirect_to new_admin_body_area_path, alert: "You could not create a body area. Please try again."
    end
  end

  private

  def body_area_params
    params.require(:body_area).permit(:name)
  end

  def require_admin
    render file: "/public/404" unless current_admin?
  end
end

app/controllers/admin/stretches_controller.rb
class Admin::StretchesController < ApplicationController
  before_action :require_admin

  def new
    @stretch = Stretch.new
  end

  def create
    @stretch = Stretch.new(stretch_params)
    if @stretch.save
      redirect_to admin_path(:current_user), alert: "#{@stretch.name} has been created!"
    else
      redirect_to new_admin_stretch_path, alert: "You cannot create that stretch without all the relevent information. Please try again."
    end
  end

  def edit
    @stretch = Stretch.find(params[:id])
  end

  def update
    @stretch = Stretch.find(params[:id])
    if @stretch.update(stretch_params)
      redirect_to stretch_path(@stretch)
    else
      redirect_to edit_admin_stretch_path(@stretch), alert: "You must fill in all information to edit this stretch."
    end
  end

  def destroy
    @stretch = Stretch.find(params[:id])
    @stretch.destroy
    redirect_to stretches_path
  end

  private

  def stretch_params
    params.require(:stretch).permit(:name, :description, :picture, body_area_ids:[])
  end

  def require_admin
    render file: "/public/404" unless current_admin?
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :require_admin

  def show
  end

  private

  def require_admin
    render file: "/public/404" unless current_admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user || User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end
end

app/controllers/body_areas_controller.rb
class BodyAreasController < ApplicationController
  def show
    params[:id] = params[:stretch_search][:body_area_id].to_i if params[:stretch_search]
    @body_area = BodyArea.find(params[:id])
    @stretches = @body_area.stretches.order(:name)
  end

  def index
    @body_areas = BodyArea.all
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = Favorite.create(stretch_id: params[:stretch_id], user_id: params[:user_id])
    # stretch = Stretch.find(params[:stretch_id])
    # flash.alert = "#{stretch.name} has been added to your favorites!"
    # Get the flash message to work.
    # Figure out how to test to make sure you can't favorite the same thing 2 times
  end

  def destroy
    favorite = Favorite.find(params[:id])
    favorite.destroy
    redirect_to user_path(current_user)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def new
    @favorite = Favorite.find(params[:favorite_id])
    @stretch = @favorite.stretch
    @note = Note.new
  end

  def create
    favorite = Favorite.find(params[:favorite_id])
    note = Note.create!(note_params)
    favorite.update_attribute :note_id, note.id
    redirect_to user_path(current_user)
  end

  def destroy
    favorite = Favorite.find(params[:favorite_id])
    note = favorite.note
    favorite.update_attribute(:note_id, nil)
    redirect_to user_path(current_user)
  end

  def edit
    @favorite = Favorite.find(params[:favorite_id])
    @note = Note.find(params[:id])
  end

  def update
    @note = Note.find(params[:id])
    @note.update(note_params)
    redirect_to user_path(current_user)
  end

  private

  def note_params
    params.require(:note).permit(:note, :favorite_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      redirect_to login_path, alert: "Login failed. Please try again."
    end
  end

  def destroy
    session.clear
    redirect_to root_path, alert: "You have been logged out."
  end
end

app/controllers/stretches_controller.rb
class StretchesController < ApplicationController
  def index
    @stretches = Stretch.all.order(:name)
    @body_areas = BodyArea.all
  end

  def show
    @stretch = Stretch.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      redirect_to new_user_path, alert: "Account creation failed. Please try again."
    end
  end

  def show
    @user = current_user
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/body_areas/new.html.erb
<h3>Create a new Body Area</h3>

<%= form_for [:admin, @body_area] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/admin/stretches/_form.html.erb
<%= form_for [:admin, @stretch] do |f| %>
  <table>
    <tr>
      <%= f.label "Body Area" %>
      <%= f.collection_check_boxes :body_area_ids, BodyArea.all, :id, :name do |cb| %>
        <% cb.label {cb.check_box + cb.text} %>
      <% end %>
    </tr>

    <tr>
      <td><%= f.label :name %></td>
      <td><%= f.text_field :name %></td>
    </tr>

    <tr>
      <td><%= f.label :description %></td>
      <td><%= f.text_field :description, size: 150 %></td>
    </tr>

    <tr>
      <td><%= f.label :picture %></td>
      <td><%= f.text_field :picture, size: 150 %></td>
    </tr>

    <tr><td><%= f.submit %></td></tr>
  </table>
<% end %>

app/views/admin/stretches/edit.html.erb
<h3>Edit <%= @stretch.name %></h3>

<%= render partial: "form" %>

app/views/admin/stretches/new.html.erb
<h3>Create a New Stretch</h3>

<%= render partial: "form" %>

app/views/admins/show.html.erb
<h3>Admin Dashboard</h3>

<ul>
  <li><%= link_to "Add a Stretch", new_admin_stretch_path %></li>
  <li><%= link_to "Create a New Body Area", new_admin_body_area_path %></li>
</ul>

app/views/body_areas/index.html.erb
<h3>Stretches by Body Area</h3>

<% @body_areas.each do |area| %>
  <h4 class='body-area-name'><%= link_to area.name, body_area_path(area) %></h4>
  <ul class='body-area-stretches'>
  <% area.stretches.each do |stretch| %>
    <li><%= link_to stretch.name, stretch_path(stretch) %>
  <% end %>
  </ul>
<% end %>

app/views/body_areas/show.html.erb
<h3>Stretches for <%= @body_area.name %></h3>

<ul>
  <% @stretches.each do |stretch| %>
    <li><%= link_to stretch.name, stretch_path(stretch) %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkStretcher</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav>
      <div>
        <div class="logo">
          <%= link_to "Stretches Home", stretches_path %>
        </div>
        <div class="stretch-search">

          <%= form_tag(body_area_path(:stretch_search), method: "get") do %>
            <%= label_tag(:stretch_search, "Find a Stretch:") %>
            <%= collection_select :stretch_search, :body_area_id, BodyArea.all, :id, :name, prompt: 'Select Body Area' %>
            <%#= text_field_tag :stretch_search %>
            <%= submit_tag("Go!") %>
          <% end %>
        </div>
      </div>
      <div class="login">
        <% if current_user %>
          <h3 class="welcome">Welcome, <%= current_user.username %>!</h3>
          <div class="logout">
            <%= link_to "Logout", logout_path, method: :delete %>
            <%= link_to "#{current_user.username}'s Profile", user_path(current_user) %>
            <% if current_user.role == 'admin' %>
              <%= link_to "Admin Dashboard", admin_path(:current_user) %>
            <% end %>
          </div>
        <% else %>
          <%= link_to "Sign In", login_path %>
          <%= link_to "Create an Account", new_user_path %>
        <% end %>
      </div>
    </nav>

    <% flash.each do |type, msg| -%>
      <%= content_tag :div, msg, class: type %>
    <% end -%>

    <%= yield %>
  </body>
</html>

app/views/notes/edit.html.erb
<h3>Edit Note on <%= @favorite.stretch.name %></h3>

<%= form_for [current_user, @favorite, @note] do |f| %>
  <%= f.label :note %>
  <%= f.text_field :note %>

  <%= f.hidden_field :favorite_id, value: @favorite.id %>

  <%= f.submit %>
<% end %>

app/views/notes/new.html.erb
<h3>Add notes for <%= @stretch.name %></h3>

<%= form_for [current_user, @favorite, @note] do |f| %>
  <%= f.label :note %>
  <%= f.text_field :note %>

  <%= f.hidden_field :favorite_id, value: @favorite.id %>

  <%= f.submit %>
<% end %>

app/views/stretches/_admin_buttons.html.erb
<% if current_user && current_user.role == 'admin' %>
  <div class="admin-buttons">
    <div class="edit-link"><%= link_to "Edit", edit_admin_stretch_path(stretch) %></div>
    <div class="delete-link"><%= link_to "Delete", admin_stretch_path(stretch), method: "delete" %></div>
  </div>
<% end %>

app/views/stretches/index.html.erb
<h1>All Suggested Stretches</h1>

<%= link_to "See All Stretches by Body Area", body_areas_path %>

<% @stretches.each do |stretch| %>
  <div class="stretches-index-stretches">
    <div class="stretch-index-names">
      <h4 class="stretch-name"><%= link_to stretch.name, stretch_path(stretch) %></h4>
      <%= stretch.description %>
    </div>
    <% if current_user %>
      <div class="btn-favorite">
        <%= link_to "Favorite", user_favorites_path(current_user, stretch_id: stretch), method: "POST" %>
        <%#= if stretch.favorites.where("username = #{current_user.username}") %>
          <%#= link_to "Remove from Favorites" user_favorite_path(current_user, stretch_id: stretch), method: "DELETE" %>
        <%# end %>
      </div>
    <% end %>
    <%= render partial: "admin_buttons", :locals => {:stretch => stretch} %>
  </div>
<% end %>

app/views/stretches/show.html.erb
<h3><%= @stretch.name %></h3>

<p><%= @stretch.description %></p>
<img src="<%= @stretch.picture %>"/>
<br />

<% if current_user %>
  <%= link_to "Favorite", user_favorites_path(current_user, stretch_id: @stretch.id), method: "POST" %>
<% end %>

<%= render partial: "admin_buttons", :locals => {:stretch => @stretch} %>

app/views/users/new.html.erb
<h3>Create a New Account</h3>

<%= form_for @user do |f| %>
  <table>
    <tr>
      <td><%= f.label :username %></td>
      <td><%= f.text_field :username %></td>
    </tr>

    <tr>
      <td><%= f.label :password %></td>
      <td><%= f.text_field :password %></td>
    </tr>

    <tr>
      <td><%= f.label :email %></td>
      <td><%= f.text_field :email %></td>
    </tr>

    <tr>
      <td><%= f.submit "Create Account" %></td>
    </tr>
<% end %>

app/views/users/show.html.erb
<h1><%= current_user.username %>'s Profile</h1>

<h3>Favorites</h3>

  <% current_user.favorites.each do |favorite| %>
    <div class='user-favored-stretches'>
      <h4 class="favored-stretch"><%= link_to favorite.stretch.name, stretch_path(favorite.stretch) %></h4><br />
      <% if favorite.note %>
        <%= favorite.note.note %>
        <div>
          <%= link_to "Remove Note", user_favorite_note_path(current_user, favorite, favorite.note), method: "DELETE" %>
          <%= link_to "Edit Note", edit_user_favorite_note_path(current_user, favorite, favorite.note) %>
        </div>
      <% else %>
        <%= link_to "Add Notes", new_user_favorite_note_path(current_user, favorite) %>
      <% end %>
      <div>
        <%= link_to "Remove from Favorites", user_favorite_path(current_user, favorite), method: "DELETE" %>
      </div>
    </div>
  <% end %>